# Docker Compose pour installer les d√©pendances npm
# Utilisation : docker compose -f docker-compose.dev-install.yml run --rm npm-install
services:
  npm-install:
    image: ${BASE_NODE_IMAGE-node:24-slim}
    container_name: convention-npm-install
    working_dir: /app
    command: npm install
    volumes:
      - .:/app
    environment:
      NODE_ENV: 'development'
